apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test # default
  name: deployment-manager
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
