apiVersion: v1
kind: Service
metadata:
  name: vessel
  namespace: test
  labels:
    app: vessel
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: vessel
  # type: LoadBalancer
  # ports:
  # - name: api-http
  #   port: 8080
  #   targetPort: "port"
  #   protocol: TCP
  # selector:
  #   app: vessel