version: '3.1'

services:

  # consignment-cli:
  #   build: ./consignment-cli
  #   environment:
  #     MICRO_REGISTRY: "mdns"

  consul:
    image:  gliderlabs/consul-server:latest
    command: "-server -bootstrap"
    # container_name: consul
    ports:
      - 8500:8500

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DB_HOST: "datastore:27017"
    # links:
    #   - consul

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DB_HOST: "datastore:27017"

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432