version: '3.1'

services:

  consul:
    image:  gliderlabs/consul-server:latest
    command: "-server -bootstrap"
    container_name: consul
    ports:
      - 8500:8500

  consignment-service:
    build: .
    image: consignment-service
    # container_name: consignment-service
    environment:
      - MICRO_SERVER_ADDRESS=:50051
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
    # depends_on:
    # - consul
    links:
      - consul
    ports:
      - 50051:50051

    # environment:
      # MICRO_ADDRESS: ":50051"
      # MICRO_REGISTRY: "mdns"
#     networks:
#       - test

# networks:
#   test:
#     driver: bridge

#     consul:
#   command: -server -bootstrap -rejoin
#   image: progrium/consul:latest
# api:
#   command: api
#   build: .
#   environment:
#     - MICRO_REGISTRY_ADDRESS=consul:8500
#   links:
#   - consul


# ###################################
# # Cousul will be used to register service which other services and discover
# consul:
#   image: consul:latest
#   command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
#   hostname: consul
#   ports:
#     - "8500:8500"
# ##################################
# # Message broker to interact with other systems
# rabbit:
#   image: rabbitmq:management
#   hostname: rabbit
#   ports:
#     - "5672:5672"
#     - "15672:15672"

# ###################################
# # Micro web to view and query service from web dashboard
# microweb:
#   image: microhq/micro
#   command: web --address=0.0.0.0:8080
#   ports:
#     - "80:8080"
#   environment:
#     - MICRO_REGISTRY=consul
#     - MICRO_REGISTRY_ADDRESS=consul
#     - MICRO_API_NAMESPACE=gomicro.api
#   links:
#     - consul
#     - service.helloworld

# ###################################
# # Our basic Helloworld service
# service.helloworld:
#   image: rajdeol/go-micro-hello-world
#   ports:
#     - "3000:3000"
#     - "8081:8080"
#   environment:
#     - MICRO_REGISTRY=consul
#     - MICRO_REGISTRY_ADDRESS=consul
#     - MICRO_BROKER=rabbitmq
#     - MICRO_BROKER_ADDRESS=amqp://guest:guest@rabbit:5672
#   links:
#     - consul
#     - rabbit
