version: '3.1'

services:

  consul:
    image:  gliderlabs/consul-server:latest
    command: "-server -bootstrap"
    container_name: consul
    ports:
      - 8500:8500

  consignment-service:
    build: .
    image: consignment-service
    environment:
      - MICRO_SERVER_ADDRESS=:50051
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
    links:
      - consul
    ports:
      - 50051:50051